services:
  - type: web
    name: techfest-website
    env: static
    buildCommand: echo "Static site build complete"
    staticPublishPath: ./
    domains:
      - techcarvaan-2025.onrender.com
    headers:
      # Security headers
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
