services:
  - type: web
    name: techfest-website
    env: static
    buildCommand: echo "Static site build complete"
    staticPublishPath: ./
    domains:
      - techcarvaan-2025.onrender.com
    headers:
      # MIME Type Headers (Critical for Render)
      - path: /assets/js/*.js
        name: Content-Type
        value: application/javascript; charset=utf-8
      - path: /assets/css/*.css
        name: Content-Type
        value: text/css; charset=utf-8
      - path: /*.js
        name: Content-Type
        value: application/javascript; charset=utf-8
      - path: /*.css
        name: Content-Type
        value: text/css; charset=utf-8
      
      # Security headers
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      
      # Cache headers for assets
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=86400
